version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  scheduler:
    build: ./scheduler-service
    ports:
      - '8080:8080'
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
  worker:
    build: ./worker-service
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
